[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#8BB9FF"
backgroundColor = "#0b0f1a"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#E6EDF3"
font = "sans serif"

[client]
caching = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true